"""
agent.py

The FitFindr planning loop. Orchestrates the three tools in response to a
natural language user query, passing state between them via a session dict.

Complete tools.py and test each tool in isolation before implementing this file.

Usage (once implemented):
    from agent import run_agent
    from utils.data_loader import get_example_wardrobe

    result = run_agent(
        query="vintage graphic tee under $30, size M",
        wardrobe=get_example_wardrobe(),
    )
    print(result["fit_card"])
    print(result["error"])   # None on success
"""
import json
from tools import search_listings, suggest_outfit, create_fit_card
from dotenv import load_dotenv
from groq import Groq
from config import MATCHING_THRESHOLD, GROQ_API_KEY, LLM_MODEL, TEMPERATURE, MAX_TOOL_ROUNDS
load_dotenv()
_client = Groq(api_key=GROQ_API_KEY)

TOOL_DEFINITIONS = [
    {
        "type": "function",
        "function": {
            "name": "search_listings",
            "description": (
                """Search the mock listings dataset for items 
                matching the description, optional size, and optional price ceiling."""
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "description": {
                        "type": "string",
                        "description": "Keywords describing the item (e.g., 'vintage graphic tee dragon')."
                    },
                    "size": {
                        "type": "string",
                        "description": "The size string to filter by (e.g., 'XL')."
                    },
                    "max_price": {
                        "type": "number",
                        "description": "The maximum price limit."
                    }
                },
                "required": ["description"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "suggest_outfit",
            "description": "Generates complete outfit combinations using the found item and the user's saved wardrobe. Call ONLY when the user explicitly asks for outfit ideas or styling help. Do NOT call it just because an item was found.",
            "parameters": {
                "type": "object",
                "properties": {},
                "required": [],
                "description": "No arguments are required. The tool uses the selected item and the wardrobe already stored in the session."
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "create_fit_card",
            "description": (
                """Takes the outfit suggestion and the found item, and generates a stylish social media caption for sharing the find.
                Call ONLY when the user explicitly asks for a caption / fit card to share. Do NOT call it just because an outfit was suggested."""
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "outfit": {
                        "type": "string",
                        "description": "The exact natural language styling advice generated by the suggest_outfit tool."},
                }
            },
            "required": ["outfit"]
        }
    }
        
]
# ── session state ─────────────────────────────────────────────────────────────

def _new_session(query: str, wardrobe: dict, existing_messages: list | None) -> dict:
    """
    Initialize and return a fresh session dict for one user interaction.

    The session dict is the single source of truth for everything that happens
    during a run — it stores the original query, parsed parameters, tool results,
    and any error that caused early termination.

    You may add fields to this dict as needed for your implementation.
    """
    if not existing_messages:
        messages = [
            {"role": "system", "content": """
            You are FitFindr, a thrift styling assistant.
            You have three independent tools. Call ONLY the tools the user actually
            asks for — do not chain them automatically.

            - search_listings: use when the user wants to find / search for a secondhand item.
            - suggest_outfit: use ONLY when the user explicitly asks for outfit ideas or styling help combine with the target piece.
            - create_fit_card: use ONLY when the user explicitly asks for a caption / fit card to share.

            Examples:
            - "vintage graphic tee under $30" → call search_listings only, then reply with the result.
            - "vintage graphic tee under $30, and give me outfit ideas" → search_listings, then suggest_outfit.
            - "find a tee under $30, suggest an outfit, and make me a fit card" → all three, in order.

            Ordering constraints (when a step IS requested):
            - You must have a search result before suggesting an outfit.
            - You must have an outfit suggestion before creating a fit card.
            If the user asks for styling or a fit card but no item has been found yet,
            run search_listings first to get a candidate.

            Use the current query and prior chat history to infer size, budget, or style
            preferences when relevant.
            If no item is found, explain the problem clearly and stop.
            Do not invent items, prices, or wardrobe pieces."""},
            {"role": "user", "content": query}
        ]
    # 2. If we have history, copy it and append the new question
    else:
        messages = existing_messages.copy()
        messages.append({"role": "user", "content": query})
    return {
        "query": query,              # original user query
        "messages": messages,        # full message history for the LLM
        "parsed": {},                # extracted description / size / max_price
        "search_results": [],        # list of matching listing dicts
        "selected_item": None,       # top result, passed into suggest_outfit
        "wardrobe": wardrobe,        # user's wardrobe dict
        "outfit_suggestion": None,   # string returned by suggest_outfit
        "fit_card": None,            # string returned by create_fit_card
        "final_reply": None,
        "error": None               # set if the interaction ended early
    }
# ──────────────────────────────────────────────
# Tool dispatch
#
# This is already complete. It routes tool calls from the LLM to the actual
# Python functions in tools.py, and returns results as JSON strings (which is
# what the Groq API expects for tool results).
# ──────────────────────────────────────────────

def dispatch_tool(tool_name: str, tool_args: dict, session: dict) -> str:
    """Route a tool call to the correct function, managing state and returning a JSON string."""
    
    # Normalize empty arguments
    if not isinstance(tool_args, dict):
        tool_args = {}
        
    print(f"  → Tool call: {tool_name}({tool_args})")
    
    # Initialize the result variable
    result = None

    if tool_name == "search_listings":
        # 1. Python Dictionary Unpacking (**): This automatically expands the dictionary 
        # into the description, size, and max_price keyword arguments.
        result = search_listings(**tool_args)
        
        # 2. State Management: Save the first result to the session vault if items were found.
        if result and isinstance(result, list):
            session["selected_item"] = result[0]
            session["search_results"] = result

    elif tool_name == "suggest_outfit":
        # 1. Retrieve the saved item and wardrobe from the session vault.
        saved_item = session.get("selected_item")
        wardrobe = session.get("wardrobe", {})
        
        # 2. Defensive check: Prevent the LLM from styling an item that doesn't exist yet.
        if not saved_item:
            result = {"error": "Cannot suggest an outfit before searching for an item."}
        else:
            outfit_str = suggest_outfit(saved_item, wardrobe)
            session["outfit_suggestion"] = outfit_str
            result = {"outfit": outfit_str}

    elif tool_name == "create_fit_card":
        # 1. Retrieve the saved item.
        saved_item = session.get("selected_item")
        
        # 2. Defensive check
        if not saved_item:
            result = {"error": "Cannot create a fit card without a selected item."}
        else:
            # We explicitly pass the outfit string generated by the LLM and our saved dictionary.
            caption_str = create_fit_card(outfit=tool_args.get("outfit", ""), new_item=saved_item)
            session["fit_card"] = caption_str
            result = {"caption": caption_str}
            
    else:
        result = {"error": f"Unknown tool: {tool_name}"}

    # Format the print statement for clean terminal debugging
    print(f"  ← Result: {json.dumps(result)[:120]}{'...' if len(json.dumps(result)) > 120 else ''}")
    
    return json.dumps(result)
# ── planning loop ─────────────────────────────────────────────────────────────

def run_agent(query: str, wardrobe: dict, chat_history: list | None = None) -> dict:
    """
    Main agent entry point. Runs the FitFindr planning loop for a single
    user interaction and returns the completed session dict.

    Args:
        query:    Natural language user request
                  (e.g., "vintage graphic tee under $30, size M")
        wardrobe: User's wardrobe dict — use get_example_wardrobe() or
                  get_empty_wardrobe() from utils/data_loader.py

    Returns:
        The session dict after the interaction completes. Check session["error"]
        first — if it is not None, the interaction ended early and the other
        output fields (outfit_suggestion, fit_card) will be None.

    TODO — implement this function using the planning loop you designed in planning.md:

        Step 1: Initialize the session with _new_session().

        Step 2: Parse the user's query to extract a description, size, and
                max_price. You can use regex, string splitting, or ask the LLM
                to parse it — document your choice in planning.md.
                Store the result in session["parsed"].

        Step 3: Call search_listings() with the parsed parameters.
                Store results in session["search_results"].
                If no results: set session["error"] to a helpful message and
                return the session early. Do NOT proceed to suggest_outfit
                with empty input.

        Step 4: Select the item to use (e.g., the top result).
                Store it in session["selected_item"].

        Step 5: Call suggest_outfit() with the selected item and wardrobe.
                Store the result in session["outfit_suggestion"].

        Step 6: Call create_fit_card() with the outfit suggestion and selected item.
                Store the result in session["fit_card"].

        Step 7: Return the session.

    Before writing code, complete the Planning Loop and State Management sections
    of planning.md — your implementation should match what you described there.
    """
    # TODO: implement the planning loop
    session = _new_session(query, wardrobe, chat_history)
    session["query"] = query

    for _ in range(MAX_TOOL_ROUNDS): 
        # Now you can safely pass session["messages"] to the API!
        response = _client.chat.completions.create(
            model=LLM_MODEL,
            messages=session["messages"], 
            tools= TOOL_DEFINITIONS, # type: ignore
            tool_choice="auto",
            temperature= TEMPERATURE
        )
        assistant_message = response.choices[0].message

    # 1) If the model answered directly, stop
        if assistant_message.content:
            session["final_reply"] = assistant_message.content
            session["messages"].append({"role": "assistant", "content": assistant_message.content})
            break
    # 2) If the model called a tool, dispatch it and append the result to the messages
        if assistant_message.tool_calls:
            session["messages"].append(assistant_message)
            
            # 3) For each tool call, run the matching Python function
            for tool_call in assistant_message.tool_calls:
                tool_name = tool_call.function.name
                tool_args = json.loads(tool_call.function.arguments)
                tool_result_json = dispatch_tool(tool_name, tool_args, session)
                
                 # 4) Append the tool result message back to the conversation
                session["messages"].append({
                    "role": "tool",
                    "tool_call_id": tool_call.id,
                    "content": tool_result_json,
                })
    if not session["final_reply"]:
        session["error"] = "The agent failed to produce a final reply within the maximum number of tool rounds."
    return session


# ── CLI test ──────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    from utils.data_loader import get_example_wardrobe, get_empty_wardrobe

    print("=== Happy path: graphic tee ===\n")
    session = run_agent(
        query="looking for a vintage graphic tee under $30",
        wardrobe=get_example_wardrobe(),
    )
    if session["error"]:
        print(f"Error: {session['error']}")
    else:
        print(f"Found: {session['selected_item']['title']}")
        print(f"\nOutfit: {session['outfit_suggestion']}")
        print(f"\nFit card: {session['fit_card']}")

    print("\n\n=== No-results path ===\n")
    session2 = run_agent(
        query="designer ballgown size XXS under $5",
        wardrobe=get_example_wardrobe(),
    )
    print(f"Error message: {session2['error']}")
