# sandbox.py
from tools import search_listings, suggest_outfit, create_fit_card
from utils.data_loader import get_example_wardrobe

# 1. Test search_listings
print("--- TESTING SEARCH ---")
results = search_listings("vintage graphic tee dragon", max_price=100.0, size="XL")
print(f"Found {len(results)} items.")
for item in results:
    print(f"- {item.get('title')} (${item.get('price')})")

# Check if we actually found items before trying to style them
if results:
    selected_item = results[0]

    # 2. Test suggest_outfit using mock data
    print("\n--- TESTING OUTFIT SUGGESTION ---")
    mock_wardrobe = get_example_wardrobe()
    
    # Pass the first found item into the outfit tool
    suggestion = suggest_outfit(selected_item, mock_wardrobe)
    print("Styling Advice:")
    print(suggestion)

    # 3. Test create_fit_card (The Happy Path)
    print("\n--- TESTING FIT CARD GENERATION ---")
    # We pass the string generated by Tool 2, and the dictionary found by Tool 1
    fit_card = create_fit_card(suggestion, selected_item)
    print("Generated Social Caption:")
    print(fit_card)

    # 4. Test create_fit_card (The Failure Mode)
    print("\n--- TESTING FIT CARD GRACEFUL DEGRADATION ---")
    # We deliberately pass an empty string to simulate Tool 2 failing
    broken_fit_card = create_fit_card("", selected_item)
    print(broken_fit_card)

else:
    print("\nSkipping outfit and fit card tests because no items were found. Try loosening your search filters.")